[package]
name = "colmenar"
version = "0.1.0"
edition = "2021"

[dependencies]
genco = "0.17.5"
heck = "0.4.1"
indexmap = "1.9.3"
openapiv3 = { version = "1.0.2", path = "../Community/openapiv3" }
serde = "1.0.160"
serde_json = "1.0.96"
serde_yaml = "0.9.21"
