[package]
name = "colmenar"
version = "0.1.0"
edition = "2021"

[dependencies]
genco = "0.17.5"
heck = "0.4.1"
openapiv3-extended = "2.2.1"
serde = "1.0.160"
serde_json = "1.0.96"
serde_yaml = "0.9.21"
